language: python
python:
  - "3.3"
  - "3.4"
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=rakutenma"
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - yukino0131@me.com
    on_success: always
    on_failure: always
